### ISSUE TITLE
i can't run script/test.py

### ISSUE THREAD

**Issue by facundolazcano** [ziyangyeh/Auto-Orth#3]
Hi, thanks for share your research.

I Have problems for run script/test.py, cfg_path is config/default.yaml, but, the script rise error.

  File "*/TANet-Pytorch/scripts/test.py", line 23, in test
    cfg = cfg.train
  File "*/TANet-Pytorch/openpoints/utils/config.py", line 21, in __getattr__
    raise AttributeError(key)
AttributeError: train

Do I need to define the train attribute in the config file?

Thanks

**Comment by ziyangyeh** [comment]
> Hi, thanks for share your research.
> 
> I Have problems for run script/test.py, cfg_path is config/default.yaml, but, the script rise error.
> 
> File "_/TANet-Pytorch/scripts/test.py", line 23, in test cfg = cfg.train File "_/TANet-Pytorch/openpoints/utils/config.py", line 21, in **getattr** raise AttributeError(key) AttributeError: train
> 
> Do I need to define the train attribute in the config file?
> 
> Thanks

Yes.
