### ISSUE TITLE
Vedo library version

### ISSUE THREAD

**Issue by Jonas-JXT** [ziyangyeh/Auto-Orth#5]
when running the preprocessing.py script, it keeps telling me that 
`AttributeError: 'Mesh' object has no attribute 'deleteCellsByPointIndex'`

Upon looking at Vedo's documentation, i noticed that this method does not exist anymore in the recent versions.
How do i solve this

Im running this on a Ubuntu vm currently

**Comment by ziyangyeh** [comment]
@Jonas-JXT 
I saw some new APIs from the latest version of Vedo. Maybe check [this one](https://vedo.embl.es/docs/vedo/pointcloud.html#Points.delete_cells_by_point_index).

**Comment by Jonas-JXT** [comment]
Your code makes use of meshes from my understanding, that method you have linked from the vedo library uses points. How would I use this method?

**Comment by ziyangyeh** [comment]
@Jonas-JXT 
`mesh.deleteCellsByPointIndex(list(set(np.asarray(mesh.cells())[np.where(mesh.celldata["Label"]==0)[0]].flatten())))`
to
`mesh.delete_cells_by_point_index(list(set(np.asarray(mesh.cells())[np.where(mesh.celldata["Label"]==0)[0]].flatten())))`

**Comment by ziyangyeh** [comment]
or
`mesh.delete_cells(with cells ids that labels are equal to 0)`

from latest version of vedo
