### ISSUE TITLE
No module named openpoints.models

### ISSUE THREAD

**Issue by Jonas-JXT** [ziyangyeh/Auto-Orth#6]
I have successfully ran the preprocess.py script, however when I run the train.py script I seem to get an error.

`Traceback (most recent call last):
  File "/home/arthurn/TANet-Pytorch-main/scripts/train.py", line 9, in <module>
    from models import LitModule
  File "/home/arthurn/TANet-Pytorch-main/models/_init_.py", line 1, in <module>
    from .submodules import *
  File "/home/arthurn/TANet-Pytorch-main/models/submodules/_init_.py", line 1, in <module>
    from .jaw_encoder import build_jaw_encoder
  File "/home/arthurn/TANet-Pytorch-main/models/submodules/jaw_encoder.py", line 1, in <module>
    from openpoints.models import build_model_from_cfg
ModuleNotFoundError: No module named 'openpoints.models'`

May I get some help on this. I am running this on a WSL ubuntu system

**Comment by ziyangyeh** [comment]
@Jonas-JXT 

openpoints: https://github.com/guochengqian/openpoints/tree/master

Refer to git submodule.

This project is no longer maintained, I am not going to answer these questions any more.

**Comment by smoothumut** [comment]
Hi @Jonas-JXT 
I couldnt make the preprocess.py script run unfortunately. Could you please help on that please?
when upper and lower meshes are merged, the new mesh's celldata["Label"] comes none. how did you solve this problem?
Thanks thanks in advance
